### ISSUE TITLE
AHRS-board has no fancontrol

### ISSUE THREAD

**Issue by bentstream** [VirusPilot/stratux-pi4#1]
Hi, I'm new on the board. Maybe this is not the right way. but I need your help.
Setup raspberry 4b 8g with stratux-pi4, everything worked fine. Since there ist no Stratux-AHRS-board available at the moment  I bought a different one and it works perfect. Happy as I was, I told a friend, and he wants the same ADSB-Receiver, with AHRS. So I insert a micro SD card in my functional System and the setup process won't work. Back to the other card, everthing is fine. The "new" card prompts something like: fancontrol arguments are missing. I marked the positions in the Makefile where fancontrol is involved and the setup process runs throug. Everything i working now, acceppt the attitude .
What am I doing worng?

**Comment by bentstream** [comment]
Different Image works

**Comment by VirusPilot** [comment]
Sorry for not reacting earlier, although this setup is derived from Stratux Europe Edition, somehow the AHRS board does not work.

**Comment by VirusPilot** [comment]
The issue may have been introduced somewhere since the last Buster release from May 2020. See [https://github.com/VirusPilot/stratux-pi4/issues/2#issue-709542038](url)
