### ISSUE TITLE
Garmin Pilot -Android 

### ISSUE THREAD

**Issue by logix727** [VirusPilot/stratux-pi4#13]
I got garmin pilot android i flashed it can see traffic on the 192.168.10.1 but garmin pilot cannot see trafffic when connected to wifi what do i do ?

**Comment by VirusPilot** [comment]
Did you select "Stratux" under "Devices" in GP? I did not renew my license but this is what I recall ...

**Comment by logix727** [comment]
There is no stratux option. :/ Android version is old. It seems

**Comment by VirusPilot** [comment]
I was just comparing the GP manuals for Android with iOS - it seems that the Android version is way behind the iOS version and does not mention any support for Stratux or similar devices.

**Comment by logix727** [comment]
Yep it's ok thanks for looking also !
