### ISSUE TITLE
LilyGO T-Beam Supreme V3.0 via OGN-Tracker Firmware supported?

### ISSUE THREAD

**Issue by cacula** [VirusPilot/stratux-pi4#14]
I just received a new LilyGO T-Beam Supreme and was wondering if it is possible to use GPS, Air pressure sensor and IMU in Stratux?
SoftRF is already [supported](https://github.com/lyusupov/SoftRF/wiki/Prime-Edition-MkIII) on this new Board but according to the [wiki](https://github.com/b3nn0/stratux/wiki/TTGO-T-Beam-Firmware-for-Stratux) the use of [OGN-Tracker](https://github.com/pjalocha/esp32-ogn-tracker) is preferred. But didn't find anyting on their side regarding the support.
Any advised would be much appreciated. Thank you!

**Comment by VirusPilot** [comment]
At this point, if you want to transmit FLARM I would recommend my SoftRF fork as this is well tested. We are currently working also on GxAirCom which may even configured through the Stratux web interface but this is still WIP. The OGN tracker is certainly an alternative which currently is the only system transmitting ADS-L. Stay tuned ...
