### ISSUE TITLE
external GPS antenna recommendation

### ISSUE THREAD

**Issue by cacula** [VirusPilot/stratux-pi4#16]
In the pictures of your [Shopping-List-v3-TX](https://github.com/VirusPilot/stratux-pi4/wiki/Shopping-List-v3-TX) you are using an external GPS antenna ( between 868 RX and 1090 RX ). Could you please add a description or link where to get it? Thanks :)

**Comment by VirusPilot** [comment]
It is the following antenna: https://gnss.store/gnss-rtk-multiband-antennas/141-elt0124.html
A bit pricy but works perfectly.
