### ISSUE TITLE
copper heatsink buy alternative

### ISSUE THREAD

**Issue by cacula** [VirusPilot/stratux-pi4#17]
In your [Shopping-List-v3-TX](https://github.com/VirusPilot/stratux-pi4/wiki/Shopping-List-v3-TX) you have 2 links for copper heatsinks. unfortunatelly the seller does not ship to germany. do you happen to know an alternative? Thanks :)

**Comment by VirusPilot** [comment]
Strange, I am based in Germany and ordered it from there but you are correct, it currently is not shipped to Germany. This is sometimes only temporarily but as an alternative I can send you one of my spare parts as soon as I am back from vacation (next week). With the fan running you may also consider just using a standard heat sing for the Pi3 and then even put the fan to the inside if there is enough space.
