### ISSUE TITLE
GPS red in Stratux 

### ISSUE THREAD

**Issue by lordvampire** [VirusPilot/stratux-pi4#18]
Built everything accourding your shoppinglist3tx.

softrf shows gps fixed, Stratux communicates with softrf but still GPS on stratux shows red…. 

Sorry am absolute noob with this ….

Could you please check what I am doing wrong… here the screenshots of both… 

![IMG_3171](https://github.com/VirusPilot/stratux-pi4/assets/1724007/05b744b6-5c29-40a8-b63e-a003fbb018b8)
![IMG_3172](https://github.com/VirusPilot/stratux-pi4/assets/1724007/35260cb7-48c4-41d2-abca-2b308a1fc6b7)
![IMG_3173](https://github.com/VirusPilot/stratux-pi4/assets/1724007/a7d67d47-2743-4ba8-b240-dd88a279d780)
![IMG_3174](https://github.com/VirusPilot/stratux-pi4/assets/1724007/e24d040b-e2f5-4532-9b6c-dcc70ba0d711)
![IMG_3175](https://github.com/VirusPilot/stratux-pi4/assets/1724007/2641b513-bdac-414f-985b-a7c62899ce4b)
![IMG_3176](https://github.com/VirusPilot/stratux-pi4/assets/1724007/62bc50c3-0f27-4673-9e07-fdcfe03079ab)

**Comment by VirusPilot** [comment]
Servus from Germany,

no worries, you have a good GPS fix from your SoftRF for your Stratux. The "official" SoftRF version that you are using does only provide GPS position over USB but no further sat information - this is why Stratux shows red. If you want to improve this you are welcome to test my SoftRF fork: https://github.com/VirusPilot/SoftRF#binaries-unstable-beta-versions-available-for-testing with no guarantee - it may render your Supreme unusable. But if you are brave enough, just download my latest beta build (https://github.com/VirusPilot/SoftRF/suites/16734763640/artifacts/956118209) and update your SoftRF over WiFi, then wait and pray ...

**Comment by lordvampire** [comment]
Habidere (westAT) as we say instead of Servus(eastAT)… 😁

just to be sure, I read something about a difference between by SX1262 to some older chips… this does not affect in any way (hopefully)…
Plus, I also tried to update firmware of the softrf by the stratux script but failed… plus2, the calibration of the G-force at stratux also gives back an error… 

greets from LOIH @D-EESL

**Comment by VirusPilot** [comment]
Habidere,

- as far as I know the Supreme is only based on sx1262
- furthermore the stratux script does no provide any SoftRF firmware (only OGN and GXAirCom) so you are stuck with my version (flash and pray..)
- calibration of the G-force: no idea, this is unrelated to SoftRF

**Comment by lordvampire** [comment]
Will report outcome…

**Comment by lordvampire** [comment]
Seems had no luck! Tbeam stays at blue led more then 5min now after flashing over WiFi the s3.ino.bin …

If it does not reboot by itself in the next 5min I will unplug usb and plug in again but expect worst scenario…. 😩

**Comment by VirusPilot** [comment]
No the ZIP file is the original SoftRF binary. Keep in mind that your Supreme needs to be connected to the Stratux USB so that it boots with my firmware. Furthermore I have changed the SoftRF WiFi AP to 192.168.4.1

**Comment by lordvampire** [comment]
Understood, I I did update the firmware while it was connected to stratux and flashed the *.ino.bin file via web. But then it did not boot anymore.
That’s why I had to flash again via USBMasstorage the original firmware….

**Comment by VirusPilot** [comment]
Just tried to upload a binary via WiFi without success, no idea at the moment. The alternative is flashing directly when connected to a PC as described here:

- connect your T-Beam S3 Supreme and put it in UF2 upload mode (press **RESET** and shortly thereafter **BOOT**)
- upload the SoftRF.ino.uf2 file to the TBEAMBOOT drive, see also: https://github.com/lyusupov/SoftRF/blob/master/software/firmware/binaries/README.md#esp32-s3

**Comment by lordvampire** [comment]
i did it now vie UF2 but still it hangs at blueLED, so does not boot correctly....

**Comment by VirusPilot** [comment]
strange

**Comment by lordvampire** [comment]
maybe i'll try to compile a version by myself?

**Comment by VirusPilot** [comment]
correct, Arduino is a mess but when correctly set up then it just works fine

**Comment by VirusPilot** [comment]
Instead of Arduino IDE you can also use VS for compile/upload but it requires Arduino CLI on your PC.

**Comment by lordvampire** [comment]
I don’t think that I am capable of doing that, as long as there is no clear howto… 

just for clarification I sent you a picture of my tbeam… maybe something is different… 
![IMG_3185](https://github.com/VirusPilot/stratux-pi4/assets/1724007/d2692fac-1ad9-4c1f-88c3-39318e901f3e)

and hey, if you want to compile the software also for my tbeam… love to send you the module in the next days… 😅😅😅

**Comment by VirusPilot** [comment]
I can certainly do that for you, just send me an email: info@stratux.de
