### ISSUE TITLE
Using fake-hwclock

### ISSUE THREAD

**Issue by brownleeb** [VirusPilot/stratux-pi4#22]
Would fixing the fake-hwclock config help with GPS satellite resolution?
I was going to work on this, but not sure which branch would be best to put it in.
Since it would be an operating system change, it would go in an image, or added to the install script.
Although, if there is no benefit, probably not worth pursuing.

**Comment by VirusPilot** [comment]
I don't see how this would help - GPS accuracy is simply dependent on the number of GNSS and sats received.

**Comment by brownleeb** [comment]
Agreed.  What I was aiming at was initial acquisition.  
Some of the apps I have use AGPS for startup and I wasnt sure if current time fed into that and would help with that inital position lock.
It wasnt really an issue, as much as wondering if it might help.  My stratux starts up with time set at Jun 2023 using the fake hwclock service.  Havent checked to see if it would help any to at a time a little closer to current.  
For example, I might fire up my stratux at home and get a good time sync a couple hours before actually flying.  I usually get a pretty fast lock, but since I usually use airplane power for my stratux, it takes a couple minutes after that to get an accurate location.
But, like I said, not even sure if having a closer startup time would help anything...
