### ISSUE TITLE
Pi4 Bookworm Install

### ISSUE THREAD

**Issue by brownleeb** [VirusPilot/stratux-pi4#23]
Just to help debug, just ran the bookworm install today.

Error on cloning WiringPi, no branch "isr" exists

It looks like the stratux makefile installs fancontrol, but the script did not create/install stratux.conf in /boot/firmware.  Fancontrol install failed.  

Also, with the new kernel, didnt the names of interfaces change?  When I ran raspi-config before installing stratux, I enabled predicable interface names in the advanced options menu.  AP+Client worked fine.  Unless this is checked for elsewhere, maybe checks for different interface names might be needed....

**Comment by VirusPilot** [comment]
Thanks for the feedback, seems that ISR is now supported by the master branch and therefore the branch has been removed. I have changed my script accordingly.

Fancontrol is still WIP particularly for Pi5 as it has its own fancontrol. The error message can be ignored.

I will check the option "predicable interface names".

**Comment by brownleeb** [comment]
I think I had the wrong impression about the predictable interface names.
Arch Linux ARM uses a different interface name, but it appears RaspiOS keeps the 'trraditional' names.  I withdraw that comment.
Fancontrol should be fine (I think) once the config file is in place prior.
I am using an "Official Raspberry Pi Case Fan" (https://www.adafruit.com/product/4794) installed on Pin 12 and it is working great, changing fan duty cycle depending on temps.
