### ISSUE TITLE
No broadcast on wlan if AP+Client is set

### ISSUE THREAD

**Issue by rudiratlos** [VirusPilot/stratux-pi4#9]
I've activated WIFI-mode AP+Client 
If iPad with sky-Map is connected to stratux WLAN (hotspot), I can see traffic on my skyMap. If iPAD connected to regualr wlan (Station mode), skymap can not see any traffic.
It looks like taht stratux app is broadcasting traffic (UDP port 4000) only on hotspot (ap0) wlan and not additionally on regular wlan.

1. Stratux version: v1.6r1-eu027
2. Stratux config:

    SDR
      - [ ] single
      - [ x] dual

    GPS
      - [x ] yes
      - [ ] no
      type:

    AHRS
      - [ ] yes
      - [x ] no

**Comment by VirusPilot** [comment]
This can't be resolved by my install script. I see that you are already in discussion with @b3nn0 on that.
